# Generated by Django 2.2.2 on 2019-06-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=128)),
                ('to_user', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=1024)),
                ('attachment', models.CharField(max_length=10000)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
