# Generated by Django 2.2.2 on 2019-06-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mail',
        ),
    ]
